local LSM = _G.LibStub('LibSharedMedia-3.0')
if not LSM then return end

--* Fonts
LSM:Register("font", "Gilroy", [[Interface\Addons\JiberishMedia\font\Gilroy.ttf]])
LSM:Register("font", "LuckiestGuy", [[Interface\Addons\JiberishMedia\font\LuckiestGuy.ttf]])
LSM:Register("font", "SigmarOne", [[Interface\Addons\JiberishMedia\font\SigmarOne.ttf]])
LSM:Register("font", "BowlbyOne", [[Interface\Addons\JiberishMedia\font\BowlbyOne.ttf]])
LSM:Register("font", "ProtestStrike", [[Interface\Addons\JiberishMedia\font\ProtestStrike.ttf]])
LSM:Register("font", "Fredoka", [[Interface\Addons\JiberishMedia\font\Fredoka.ttf]])
LSM:Register("font", "GothamNarrowUltra", [[Interface\Addons\JiberishMedia\font\GothamNarrowUltra.ttf]])
LSM:Register("font", "Catamaran-Black", [[Interface\Addons\JiberishMedia\font\Catamaran-Black.ttf]])
LSM:Register("font", "Changa-ExtraBold", [[Interface\Addons\JiberishMedia\font\Changa-ExtraBold.ttf]])
LSM:Register("font", "Raleway-Black", [[Interface\Addons\JiberishMedia\font\Raleway-Black.ttf]])
LSM:Register("font", "SpaceGrotesk-Bold", [[Interface\Addons\JiberishMedia\font\SpaceGrotesk-Bold.ttf]])
LSM:Register("font", "Urbanist-Black", [[Interface\Addons\JiberishMedia\font\Urbanist-Black.ttf]])
LSM:Register("font", "BigNoodleToo", [[Interface\Addons\JiberishMedia\font\BigNoodleToo.ttf]])
LSM:Register("font", "TacOne", [[Interface\Addons\JiberishMedia\font\TacOne.ttf]])
LSM:Register("font", "GasoekOne", [[Interface\Addons\JiberishMedia\font\GasoekOne.ttf]])
LSM:Register("font", "RussoOne", [[Interface\Addons\JiberishMedia\font\RussoOne.ttf]])
LSM:Register("font", "Poppins-Black", [[Interface\Addons\JiberishMedia\font\Poppins-Black.ttf]])
LSM:Register("font", "KMT-GothamXN_Ultra", [[Interface\Addons\JiberishMedia\font\KMT-GothamXN_Ultra.ttf]])
LSM:Register("font", "Rubik-BlackItalic", [[Interface\Addons\JiberishMedia\font\Rubik-BlackItalic.ttf]])
LSM:Register("font", "Rubik-Black", [[Interface\Addons\JiberishMedia\font\Rubik-Black.ttf]])
LSM:Register("font", "Rubik-Bold", [[Interface\Addons\JiberishMedia\font\Rubik-Bold.ttf]])
LSM:Register("font", "Rubik-Regular", [[Interface\Addons\JiberishMedia\font\Rubik-Regular.ttf]])
LSM:Register("font", "Lixdu", [[Interface\Addons\JiberishMedia\font\Lixdu.ttf]])
LSM:Register("font", "Kabisat", [[Interface\Addons\JiberishMedia\font\Kabisat.ttf]])

--* Statusbars
LSM:Register("statusbar", "Jiberwatch", [[Interface\Addons\JiberishMedia\statusbar\Jiberwatch.tga]])
LSM:Register("statusbar", "JiberwatchFlip", [[Interface\Addons\JiberishMedia\statusbar\JiberwatchFlip.tga]])
LSM:Register("statusbar", "20Bushido", [[Interface\Addons\JiberishMedia\statusbar\20Bushido.tga]])
LSM:Register("statusbar", "NewBushidoHealth", [[Interface\Addons\JiberishMedia\statusbar\NewBushidoHealth.tga]])
